import { Target, TargetEvent, ExtensionInfo } from './ext-events';

export type Protocol = 'http' | 'https' | 'node:http' | 'node:https';
export type OriginalHeaders = Record<string, string | string[] | undefined>;
export type RequestOptions = Record<string, unknown>;

export type NetworkPhase =
  | 'request:pre' // block at the url level, avoid any potential leakage if the extension chose to stream exfiltrated data
  | 'request:post' // in case the body isn't in the options and is produced later
  | 'response'
  | 'error'
  | 'timeout'
  | 'close'
  | 'connect'
  | 'upgrade';

/**
 * Handles all network-related events generated by the hooks and relays them to the network channel
 * Note: it may be useful to distinguish between the different phases of the request/response cycle
 * instead of using a mega structure like this
 */
export class NetworkEvent extends TargetEvent<Target.NETWORK> {
  readonly protocol: Protocol;
  readonly url: string;
  readonly phase: NetworkPhase;

  // request-specific
  readonly method?: string;
  readonly options?: RequestOptions;

  // response / connect / upgrade
  readonly statusCode?: number;
  readonly headers?: OriginalHeaders;
  readonly upgradeTo?: string; // 101 status code

  // body capture, limited to NETWORK.MAX_CAPTURE_BYTES
  readonly payload?: string;
  readonly truncated: boolean;

  // allows request<->response match
  readonly correlationId: string;

  constructor(
    protocol: Protocol,
    url: string,
    phase: NetworkPhase,
    hookFile: string,
    extension: ExtensionInfo,

    method?: string,
    options?: Record<string, unknown>,

    statusCode?: number,
    headers?: OriginalHeaders,
    upgradeTo?: string,

    payload?: string,
    truncated?: boolean,

    correlationId?: string,
    timestamp?: number,
  ) {
    super(Target.NETWORK, extension, hookFile, timestamp);

    this.protocol = protocol;
    this.url = url;
    this.phase = phase;

    this.method = method;
    this.options = options;

    this.statusCode = statusCode;
    this.headers = headers;
    this.upgradeTo = upgradeTo;

    this.payload = payload;
    this.truncated = !!truncated;

    this.correlationId = correlationId ?? this.eventId;
  }

  isRequestPhase(): boolean {
    return this.phase === 'request:pre' || this.phase === 'request:post';
  }
  isResponsePhase(): boolean {
    return this.phase === 'response';
  }

  toJSON(): string {
    return JSON.stringify({
      eventId: this.eventId,
      timestamp: this.timestamp,
      eventType: this.eventType,
      extension: this.extension,
      hookFile: this.hookFile,

      protocol: this.protocol,
      url: this.url,
      phase: this.phase,
      method: this.method,

      statusCode: this.statusCode,
      headers: this.headers,
      upgradeTo: this.upgradeTo,

      payload: this.payload,
      truncated: this.truncated,
      correlationId: this.correlationId,
    });
  }
}
