/**
 * Security Events generated by the detection engine when suspicious activity is found
 * These are higher-level events that contain IoCs and findings from analyzed extension events
 */
import { NetworkRuleType } from '../../detection/network-rules';
import { ProcessRuleType } from '../../detection/process-rules';
import { TaskRuleType } from '../../detection/task-rules';
import { ExtensionInfo, WorkspaceInfo, TargetEvent, Target, Timestamp } from './ext-events';

export enum SeverityLevel {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
}

const SEVERITY_ORDER = { [SeverityLevel.LOW]: 1, [SeverityLevel.MEDIUM]: 2, [SeverityLevel.HIGH]: 3 };

/**
 * Compare two severity levels
 * @returns positive if severity1 > severity2, negative if severity1 < severity2, 0 if equal
 */
export function compareSeverity(severity1: SeverityLevel, severity2: SeverityLevel): number {
  return SEVERITY_ORDER[severity1] - SEVERITY_ORDER[severity2];
}

export function getHighestSeverity(severities: SeverityLevel[]): SeverityLevel {
  return severities.reduce(
    (highest, current) => (compareSeverity(current, highest) > 0 ? current : highest),
    SeverityLevel.LOW,
  );
}

/**
 * IoC found in the extension event
 * We suppose each IoC is surfaced by a single rule.
 * If multiple rules are triggered, we will create multiple IoCs.
 */
export interface IoC {
  finding: string;
  rule: string; // triggered rule
  description: string;
  confidence: number; // we'll see how to set this
  severity: SeverityLevel; // severity of this specific IoC
}

export interface Verdict {
  allowed: boolean;
}

/**
 * Security Event generated by the detection engine when a threat is detected
 */
export class SecurityEvent {
  public readonly secEventId: string;
  public readonly timestamp: Timestamp;
  public readonly severity: SeverityLevel;
  public readonly securityEventType: ProcessRuleType | NetworkRuleType | TaskRuleType;

  public readonly extension?: ExtensionInfo;
  public readonly workspace?: WorkspaceInfo;

  public readonly iocs: IoC[];

  public readonly originalEvent: TargetEvent<Target>;

  constructor(
    originalEvent: TargetEvent<Target>,
    source: ExtensionInfo | WorkspaceInfo,
    severity: SeverityLevel,
    securityEventType: ProcessRuleType | NetworkRuleType | TaskRuleType,
    iocs: IoC[],
    timestamp: Timestamp = Date.now(),
  ) {
    this.secEventId = originalEvent.eventId;
    this.timestamp = timestamp;
    this.severity = severity;

    if (originalEvent.eventType === Target.WORKSPACE) {
      this.workspace = source as WorkspaceInfo;
    } else {
      this.extension = source as ExtensionInfo;
    }

    this.iocs = iocs;
    this.originalEvent = originalEvent;
    this.securityEventType = securityEventType;
  }

  /**
   * Get the most pressing IoC (highest severity, then highest confidence)
   */
  getPrimaryIoC(): IoC {
    const highestSeverity = getHighestSeverity(this.iocs.map((ioc) => ioc.severity));
    const highestSeverityIoCs = this.iocs.filter((ioc) => ioc.severity === highestSeverity);

    return highestSeverityIoCs.reduce(
      (max, ioc) => (ioc.confidence > max.confidence ? ioc : max),
      highestSeverityIoCs[0],
    );
  }

  // customize it later to grab attention cuz they have the attention span of a goldfish, myself included
  getSummary(): string {
    const primaryIoC = this.getPrimaryIoC();
    return `\t- Triggered Rule: ${primaryIoC.rule}\n\t- Rule description: ${primaryIoC.description}\n\t- Severity: ${primaryIoC.severity}`;
  }

  getSecurityEventData(): Record<string, any> {
    return {
      secEventId: this.secEventId,
      timestamp: this.timestamp,
      extension: this.extension,
      workspace: this.workspace,
      iocs: this.iocs,
      originalEventData: this.originalEvent.toJSON,
      summary: this.getSummary(),
    };
  }
}
